---
- name: copy jenkins lts key
  ansible.builtin.copy:
    src: /files/rhel/rhel_lts_jenkins.io.key
    dest: /tmp/jenkins.io.key
    owner: root
    group: root
    mode: '0644'
  when: jenkins_lts

- name: copy jenkins lts apt conf
  ansible.builtin.copy:
    src: /files/rhel/rhel_lts_jenkins.list
    dest: /etc/yum.repos.d/jenkins.repo 
    owner: root
    group: root
    mode: '0644'
  when: jenkins_lts

- name: copy jenkins weekly key
  ansible.builtin.copy:
    src: /files/rhel/rhel_weekly_jenkins.io.key
    dest: /tmp/jenkins.io.key
    owner: root
    group: root
    mode: '0644'
  when: jenkins_weekly

- name: copy jenkins weekly apt conf
  ansible.builtin.copy:
    src: /files/rhel/rhel_lts_jenkins.list
    dest: /etc/yum.repos.d/jenkins.repo
    owner: root
    group: root
    mode: '0644'
  when: jenkins_weekly

- name: install jenkins
  ansible.builtin.apt:
    pkg:
    - fontconfig
    - openjdk-11-jre
